### ISSUE TITLE
done is not a function error

### ISSUE THREAD

**Issue by demisx** [megahertz/gulp-task-doc#2]
After upgrading from 1.0.8 version I've started seeing the following error:

``` sh
$ gulp help
... ... ... # skipped for brevity
[08:12:27] TypeError: done is not a function
    at C:\cygwin64\home\dmoore\projects\sites\webcms2-core-mirror-colddata\node_modules\gulp-task-doc\index.js:73:5
    at C:\cygwin64\home\dmoore\projects\sites\webcms2-core-mirror-colddata\gulpfile.js:573:13
    at taskWrapper (C:\cygwin64\home\dmoore\projects\sites\webcms2-core-mirror-colddata\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at asyncRunner (C:\cygwin64\home\dmoore\projects\sites\webcms2-core-mirror-colddata\node_modules\async-done\index.js:36:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
```

Rolling back to 1.0.8 makes the error go away.

**Comment by megahertz** [comment]
Thanks, fixed in v1.0.11
